### PR TITLE
[feat] close app if not admin

### PR DESCRIPTION
**Pull request by Cryotechnic**
This PR partially addresses #67 by adjusting the following:

- Adds logging to let the user know that the application is not running under admin
- Kills the application after user presses a key in console window

## ToDo:
- Implement some sort of GUI element to allow the user to restart with admin if they do not have Console enabled
OR
- Implement auto-restart if the application detects incorrect permission levels set
- Update README/wiki if the user encounters this error during development, with how to fix it

### CODE REVIEW

**Comment by Cryotechnic** [comment]
The app should now automagically restart if it does not have admin privileges. This option does not prompt the user for a restart as I felt that it creates unnecessary work for both the developers (we'd have to implement a button/notification system) as well the user.

**Comment by neon-nyan** [comment]
Hi @Cryotechnic,

As per my recent comment in this issue: #67, I've made a branch to implement the "Run as admin" prompt in the ``Main()`` method level so the app is running as admin from the start.
You can check out the commit here: https://github.com/neon-nyan/Collapse/commit/c3bb1a4699d187073057cbbc48448f3f43688aca

## Preview
https://user-images.githubusercontent.com/30566970/210075039-e1c95dd0-6e9d-4815-87c4-b126f8a3b642.mp4

**Comment by Cryotechnic** [comment]
Hey, sorry for the delayed response. As we are coming into the new year, I have family commitments so I have had less time to work on this project. I should have some time later today to properly test this feature. Thank you for your help with this!

**Comment by Cryotechnic** [comment]
Ok got the chance to take a look at it on my end. Everything seems to work as intended if you run it after compilation, as the window appears normally. That being said, if you run it in Debug in VS2022, the `Program.cs` method has no way of knowing what the previous scope of the application is, which I believe is the reason as to why it fails.

Demo:

https://user-images.githubusercontent.com/9833218/210125581-d05f9e26-2dcd-460a-903b-86ccbcc3f1d7.mp4

Screenshot of error:
image

While I do not believe that this is critical to the app working well, it would be nice if we could take this issue into account should a developer want to test it themselves.

Another question I have is if it would be possible to style it as a WinUI MessageBox rather than a built-in Microsoft one. This is again, not a requirement, but just to keep our design language consistent.

Aside from that, everything looks great!

**Comment by neon-nyan** [comment]
Seems like the arguments from the ``Main()`` to the admin check code method doesn't get concatenate properly and causing the app to not recognize it as a valid list of arguments.

Anyway, I don't see a line where it sets the ``Arguments`` property while initializing ``ProcessStartInfo()`` inside of the ``Process()`` or did you not commit the changes yet? 🤔

**Comment by neon-nyan** [comment]
Another addition. Since we should necessarily to run this launcher as administrator from the start, can we also implement this admin check method on the ``Main()`` level (as based on this commit: https://github.com/neon-nyan/Collapse/commit/c3bb1a4699d187073057cbbc48448f3f43688aca)

**Comment by Cryotechnic** [comment]
> Seems like the arguments from the `Main()` to the admin check code method doesn't get concatenate properly and causing the app to not recognize it as a valid list of arguments.
> 
> Anyway, I don't see a line where it sets the `Arguments` property while initializing `ProcessStartInfo()` inside of the `Process()` or you haven't commit the changes yet? 🤔

I'm assuming you fixed this in c3bb1a4699d187073057cbbc48448f3f43688aca? Asking since I see the `Arguments` added to the codebase, unless you want it for `ApplyUpdate` as well?

**Comment by neon-nyan** [comment]
Yep, the recent commit contains changes to add the ``Arguments`` to pass it from an external ``Process`` call.

So, the goal of that commit is actually giving the "administrator check" on the ``Main()`` method instead of implementing it to each particular method. So the app will be launched as an administrator from the beginning.

**Comment by Cryotechnic** [comment]
> Yep, the recent commit contains changes to add the `Arguments` to pass it from an external `Process` call.
> 
> So, the goal of that commit is actually giving the "administrator check" on the `Main()` method instead of implementing it to each particular method. So the app will be launched as an administrator from the beginning.

Does this mean that we're good to merge this then or is there anything missing? A bit confused XD

**Comment by neon-nyan** [comment]
For now, I think it's enough. The rest will be added by me.
I will be merging this in an hour or so.

**Pull request merged**
