### PR TITLE
[WIP] Keyboards shortcuts

### PR DESCRIPTION
**Pull request by gablm**
A working attempt to implement a way of switching games using keyboard shortcuts.
CTRL + [1 to 3] to change game.

Based on issue #151

### CODE REVIEW

**Comment by Cryotechnic** [comment]
Heyo, thanks for your contributions again!

While your PR constitutes a complete solution, if possible, adding the following features would, I believe, add more customizability to Collapse:

- Add an option to toggle keyboard shortcuts ON/OFF
- Add a "Keyboard Shortcuts" popup, similarly to what Discord uses:
- Look into having region toggles. I wouldn't mind not having this, but allowing 

The rest of your code looks good. Let me know what you think.

**Comment by gablm** [comment]
I do agree that those 3 things would complement the shortcuts and shouldn't be difficult to add, so I will try to implement them.
Do you mind if I create a post in Collapse's Discord PR forum?

**Comment by Cryotechnic** [comment]
Go for it! That's what it's there for :))

**Comment by gablm** [comment]
Given I am working on a swappable key bind implementation and it may take a while, I think it's better to clos this PR for now.

When the improved implementation is ready I will open a new PR.

**Pull request closed without merging**
