### PR TITLE
Playtime counter

### PR DESCRIPTION
**Pull request by gablm**
The counter updates even when not in it's region.

It uses a key inside the game's own registry folder. The value is saved as a integer in seconds.
 - There is a write every minute after a game is started (to keep a somewhat accurate track of minutes when changing regions and if the Launcher crashes) [*1] [*2]
 - When closing the game, the actual playtime value is written, based in increments of 1s.
 - One read once you change to a region and one read after a minute.
 - One write when clicking reset or update.
 - One read when clicking the time counted if the game is not running (to make sure the editing values are the current ones).
 
Time won't be counted if the game was not started using Collapse and Playtime can't be edited while a instance of that game is running.

[*1] The value "saveFrequencyinSeconds" in the function "StartPlaytimeCounter" can be changed to determine the time interval that a "dummy" value is saved to the registry.

[*2] Dynamic Playtime Update can be disabled by changing "dynamicUpdate" to false in the function "AutoUpdatePlaytimeCounter".

### CODE REVIEW

**Comment by bagusnl** [comment]
Great work as always! I will check on the behavior later and hopefully we can merge this awesome feature
In the meantime, you can start moving the locals to Hi3Helper.Core so its easier to manage and translate in the future.
Again, great work :yatta:

**Comment by Cryotechnic** [comment]
Tested and LGTM, are we set on pushing this for 1.70? @gablm @bagusnl @neon-nyan

**Comment by gablm** [comment]
Hey @Cryotechnic, 
After your comment I decided to do another review of the code and found that it was actually not working for HI3.
I fixed it and added some confirmation modals to the reset and change button while I was at it.
Would you be able to test it again, if possible?

**Comment by Cryotechnic** [comment]
> Hey @Cryotechnic, 
> After your comment I decided to do another review of the code and found that it was actually not working for HI3.
> I fixed it and added some confirmation modals to the reset and change button while I was at it.
> Would you be able to test it again, if possible? 

Sure, weird though because it was fine on my machine but I'll give it a try and let you know in a bit.

**Comment by Cryotechnic** [comment]
@gablm Apologies for the delay. This no longer causes any issues with HI3 & works as intended. Maybe we can display a different message for changing vs. resetting the playtime?

**Comment by gablm** [comment]
Hey @Cryotechnic, 
No worries, thanks for testing again.

About the message displayed, I'm assuming you mean the one in the confirmation models. If so, do you have any suggestions of messages for those?

**Comment by Cryotechnic** [comment]
> About the messages displayed, I'm assuming you mean the one in the confirmation modals. If so, do you have any suggestions of messages for those?

For change: "Changing your playtime means overwriting the current value with the one you just inputted. Do you wish to proceed?

Note: This has no impact on how Collapse operates and you can change this value again at any time when not playing the game."

For resetting: "Resetting your playtime means setting the playtime counter back to 0. This is a **destructive** action, meaning that you cannot undo this once you confirm. Do you wish to proceed?

Note: This has no impact on how Collapse operates and you can change this value again at any time when not playing the game."

**Comment by Cryotechnic** [comment]
Going to go ahead and merge this in preparation for releasing Collapse 1.70.9. Thanks for your contributions!

**Pull request merged**
