### PR TITLE
[feat] Added bool flag for Updater fallbackRepoURL using CDN

### PR DESCRIPTION
**Pull request by Cryotechnic**
This PR directly addresses #64 by implementing a fallback github repository URL through `Statically`, a CDN provider which (should, in theory) works in countries including China and other countries with geo-restricted firewall rules placed on the internet. 

The first phase of this implementation touches upon the `Updater` component, which enables the Launcher to pull through the CDN and skip having to go through GitHub, which is geo-restricted and does not work in the affected countries mentioned above. Some notes/ideas/areas to improve:

- Implement a way for the user to force use the CDN in the launcher settings, either through an arg/toggle available only in Settings (which probably require an app restart?) for troubleshooting/to fix performance issues that they may be having with GitHub
- Implement a way to check if GitHub is up, if it is not, switch to CDN (which caches files)
- Implement a dialog for the user (WinUI if possible), which prompts them if they want to retry the operation using CDN
- Apply CDN for future implementations (which are not `Updater`-related)

Let me know if we're missing anything. The feature set outlined above needs further elaboration/discussion so if needed, feel free to open an issue or to keep this PR open for future phases of this implementation.

Note: I rewrote and formatted the code in a better way, which is why the branch is different from the one linked in #64. The code remains very similar though. Feel free to test and let me know if there are any issues you encountered.

### CODE REVIEW

**Comment by neon-nyan** [comment]
LGTM! Anyway we should implement the fallback mechanism while loading the metadata file for the first time too. But it will be in another time.
For now, can I merge this PR?

**Comment by Cryotechnic** [comment]
> LGTM! Anyway we should implement the fallback mechanism while loading the metadata file for the first time too. But it will be in another time. For now, can I merge this PR?

Adding metadata is not that complicated so I can probably get that done for today. Let me commit those changes and then you can merge.

**Comment by Cryotechnic** [comment]
Not ready yet as I'm still missing 2 fields (`AppGameRepairIndexURLPrefix` & `AppGameRepoIndexURLPrefix`), but these should be added in the next hour or so.

Some notes:
- `AppGameConfigURLPrefix` is no longer used as we have switched to V2. Might be better off to just remove that field but I haven't touched it as I am unsure.
- We could also add a toggle button in `Launcher Settings` to force the use of CDN at all times (as a debug feature, if anything, or as a Launch Argument when starting Collapse)

Let me know what you think!

**Comment by Cryotechnic** [comment]
@neon-nyan When testing & if we put this in production, we'll most likely first need to downsize the repository size to <50MB, as `Statically` & `jsDelivr`, the CDN providers which I was looking at, have a total repo size limit which make it impossible for them to cache larger files such as `index` in `repair_indexes`. 

There are a couple of potential solutions for this:
- We reduce the overall filesize of the repair metadata which make it available for caching by larger CDN providers
- We host it ourselves somewhere and make sure that it is accessible worldwide (maybe through your proxy?)
- We can also just use HDiff, as we were talking about in #69 which would replace the current repair index metadata mechanism that we are using.

I've pushed my changes but am open to suggestions. Feel free to test the commit on my repo @ a2aaf41cfcbe0d0b8d839e3895db231026da7b29

**Comment by LYF511** [comment]
Hi, I'm a player from China.

In China, we often use [gh-proxy](https://github.com/hunshcn/gh-proxy) to access github, so there are many **acceleration sources** for **public welfare**. (This shows that you can't **abuse** them) For example, the [moeyy](https://github.moeyy.xyz/) acceleration source, you only need to add `https://github.moeyy.xyz/` before the normal raw link, such as `https://raw.githubusercontent.com/neon-nyan/CollapseLauncher-ReleaseRepo/main/metadata/repair_indexes/Hi3CN/6.3.0/index` => `https://github.moeyy.cn/https://raw.githubusercontent.com/neon-nyan/CollapseLauncher-ReleaseRepo/main/metadata/repair_indexes/Hi3CN/6.3.0/index`. But not all acceleration sources are accessed in this way. For specific logic, please refer to [this](https://greasyfork.org/scripts/412245-github-%E5%A2%9E%E5%BC%BA-%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD/code/Github%20%E5%A2%9E%E5%BC%BA%20-%20%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD.user.js) script on greasyfork.

So, could you let users customize the github acceleration source on the setup page, or use the command line to specify the acceleration source? If so, thank you very much!!

By the way, my English is not very good, so please forgive me for using Baidu Translator. If there is something you can't understand, please point out.

I really like this project!!

**Comment by Cryotechnic** [comment]
> Hi, I'm a player from China.
> 
> In China, we often use [gh-proxy](https://github.com/hunshcn/gh-proxy) to access github, so there are many **acceleration sources** for **public welfare**. (This shows that you can't **abuse** them) For example, the [moeyy](https://github.moeyy.xyz/) acceleration source, you only need to add `https://github.moeyy.xyz/` before the normal raw link, such as `https://raw.githubusercontent.com/neon-nyan/CollapseLauncher-ReleaseRepo/main/metadata/repair_indexes/Hi3CN/6.3.0/index` => `https://github.moeyy.cn/https://raw.githubusercontent.com/neon-nyan/CollapseLauncher-ReleaseRepo/main/metadata/repair_indexes/Hi3CN/6.3.0/index`. But not all acceleration sources are accessed in this way. For specific logic, please refer to [this](https://greasyfork.org/scripts/412245-github-%E5%A2%9E%E5%BC%BA-%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD/code/Github%20%E5%A2%9E%E5%BC%BA%20-%20%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD.user.js) script on greasyfork.
> 
> So, could you let users customize the github acceleration source on the setup page, or use the command line to specify the acceleration source? If so, thank you very much!!
> 
> By the way, my English is not very good, so please forgive me for using Baidu Translator. If there is something you can't understand, please point out.
> 
> I really like this project!!

Heyo, thanks for your interest in the project! I'll be testing this in the next couple of days (busy with school currently) but wanted to let you know that this is being looked into. Will keep you posted of any changes made. Implementing a new page could take some time, so we might resort to using custom arguments, but need to look into it. @neon-nyan

**Comment by LYF511** [comment]
> 
> Heyo, thanks for your interest in the project! I'll be testing this in the next couple of days (busy with school currently) but wanted to let you know that this is being looked into. Will keep you posted of any changes made. Implementing a new page could take some time, so we might resort to using custom arguments, but need to look into it. @neon-nyan

That's OK! I have many new ideas about this project. If possible, I will try to make contributions!

**Comment by Cryotechnic** [comment]
Ok, haven't posted an update in a while but I have been working on it slowly but surely to make sure it (hopefully) is on track for the next major release of Collapse. Currently, I have added an extra step in the setup process to accommodate for this. While the value is set,  it is never retrieved (yet) and thus the requests are not yet being sent based on the user selection. The start point would be to have the user select from a pre-selected list, which have been verified to be working. Maybe in the future, should development time allow, a custom dialog could be implemented to allow the users to manually input their own proxy/CDN service. 

Furthermore, the page is currently a duplicate of the 1st page, minus the text and the "Locate Folder" button (the logo placement and text placement remain the same. Furthermore, the strings are placeholders as we will need to find a way to accurately describe what this feature does.

I felt that integrating as part of the setup is the best way to expose this feature to the user, as obscuring it behind settings would make it more challenging to implement globally and could cause user confusion as to this feature's functionality. Integrating it as part of the setup allows the user to select the best possible option for them. 

The main current drawback to this, is that once the user goes through the initial setup process, they have no way of getting back to this screen and changing the CDN, which means that, should it go down, we will need to either implement a mechanism for trying to connect via another route, or to give them an option in the Launcher Settings to change their CDN. 

My next step will be to enforce the selection across all current URLs that are used in the environment to re-route to the user's selected CDN. The step after that will be to implement a dropdown inside the Launcher Settings to give the user the ability to change the CDN at any time (this may need to require an application restart, but that is TBD).

Preview:
image

@neon-nyan What do you think of this, would love to hear your thoughts.

**Comment by neon-nyan** [comment]
Hi @Cryotechnic,

Happy to hear about the progress.
Yes, this is the better way to just let the user to select the alternative repo rather than using ``try catch`` approach which is taking the load time much longer.

Also, I suggest you to set the ``AppGameRepoIndexURLPrefix`` while selecting the repo dropdown so we don't need to bother to add another fallback variable for the URL string. By doing this, the load process would be basically the same without any changes to the loading mechanism code.

**Comment by Cryotechnic** [comment]
> Hi @Cryotechnic,
> 
> Happy to hear about the progress. Yes, this is the better way to just let the user to select the alternative repo rather than using `try catch` approach which is taking the load time much longer.
> 
> Also, I suggest you to set the `AppGameRepoIndexURLPrefix` while selecting the repo dropdown so we don't need to bother to add another fallback variable for the URL string. By doing this, the load process would be basically the same without any changes to the loading mechanism code.

Should be implemented now in c30a6dbfc3141588966d8c681ca8d53930e2055d. It now updates correctly and should work in most scenarios. @neon-nyan What would be the best thing to do if the CDN is down? I was thinking that we could have a popup like for Privilege Elevation but not sure if it's even required.

**Comment by neon-nyan** [comment]
I think we can implement some of a check on start-up. If the URL is invalid or throws an error, it will automatically fall back to the original or another mirror.

**Comment by Cryotechnic** [comment]
> I think we can implement some of a check on start-up. If the URL is invalid or throws an error, it will automatically fall back to the original or another mirror.

Should be all in [c625ac3](https://github.com/neon-nyan/Collapse/pull/71/commits/c625ac38b9249df63f64c79b100121dd40172837)

I think outside of that, we'd just need to provide a description for the feature as well as localization for it and it should be ready to ship in the next major release.

**Comment by Cryotechnic** [comment]
Ok, this ([3ce29bb](https://github.com/neon-nyan/Collapse/pull/71/commits/3ce29bb3dc306ee3672223aa166f236ff05cc1bc)) should be the final one now. Missing Localization strings, so will need to ask the other folks to do a pass on that, but aside from that, we're only missing the explanation for the CDN during the setup process @neon-nyan.

**Comment by neon-nyan** [comment]
Hi @Cryotechnic,

As discussed in Ironmaiden Discord Server, I think we are good to merge this PR for now and as I already said in the chat before, there might be some code refactoring going on and I'll be working on this.

Thank you for the contribution!

**Pull request merged**
