### PR TITLE
Make launcher always run as administrator + Add Vietnamese [vi-VN] Translation

### PR DESCRIPTION
**Pull request by kleqing**
Basically, I think may be it's not useful for most people but a some people didn't want to open launcher with a required prompt to run this as admin and they have to re-open launcher twice!

image

Also if this pull request didn't acepted, can I add Vietnamese (vi-VN) to this launcher?

### CODE REVIEW

**Comment by kleqing** [comment]
> It was supposed to be added inside the app manifest file but there was a conflict with preview WindowsAppSDK's own app manifest file and causing build issues.
-  My english is not good too much so I think I should sorry about this one but I just thought this idea when I installed this launcher, I just found how to make it run as admin but i didn't expect this one._.

Btw, can you make the installer that after the installation it created a shortcut which will run the launcher as adminstrator?
I can created one using Innosetup.

- I think that I will make it soon! Maybe it will cost a little bit of time to translate all!
> Yes, of course you can. Please make another PR for the translation so we can make it on track.

**Comment by neon-nyan** [comment]
> My english is not good too much so I think I should sorry about this one but I just thought this idea when I installed this launcher, I just found how to make it run as admin but i didn't expect this one._.

Don't worry, You're doing good! 😃 

> Btw, can you make the installer that after the installation it created a shortcut which will run the launcher as adminstrator?
I can created one using Innosetup.

Actually, we've already made one for this. You can check out [**this script**](https://github.com/neon-nyan/Collapse/blob/main/InstallerProp/DeployInstaller-Stable.iss).

**Comment by neon-nyan** [comment]
I think we can merge this already. But since there are many conflicts in this PR, I will cherry-pick only the necessary commit into both **#main** and **#memory-squash** branches.

**Comment by kleqing** [comment]
> Actually, we've already made one for this. You can check out [**this script**](https://github.com/neon-nyan/Collapse/blob/main/InstallerProp/DeployInstaller-Stable.iss).

- I think we should add some parameter for the *.iss file. I didn't sure that if it work or not but better than do nothing^^

**Comment by neon-nyan** [comment]
### Anyway, as I've said before:
> ### Additional information about the translation PR:
> Please use [**#memory-squash**](https://github.com/neon-nyan/Collapse/tree/memory-squash) as a base for your PR. There are many changes going on since the last changes in this **#main** branch.

What I meant was for your new translation PR later and not this PR. You can change the base branch for this PR back to **#main** to avoid the conflicts so we are able to merge this PR 🦖

**Comment by neon-nyan** [comment]
Okay, I think we are good to go. Can I merge this PR for now?

**Comment by kleqing** [comment]
> ### Anyway, as I've said before:
> 
> > ### Additional information about the translation PR:
> 
> > Please use [**#memory-squash**](https://github.com/neon-nyan/Collapse/tree/memory-squash) as a base for your PR. There are many changes going on since the last changes in this **#main** branch.
> 
> 
> 
> What I meant was for your **new translation** PR later and not this PR. You can change the base branch for this PR back to **#main** to avoid the conflicts so we are able to merge this PR 🦖 

- Sorry about that, I didn't notice that I changed to main branch!😓

**Comment by neon-nyan** [comment]
> Sorry about that, I didn't notice that I had changed to the main branch!😓

You've done it right previously but I noticed you're changing the base branch for this PR back again to **#memory-squash**.
Could you please change it back to **#main**? 😅

**Comment by kleqing** [comment]
> > Sorry about that, I didn't notice that I had changed to the main branch!😓
> 
> 
> 
> You've done it right previously but I noticed you're changing the base branch for this PR back again to **#memory-squash**.
> 
> image
> 
> 
> 
> Could you please change it back to **#main** again? 😅 

- Sure! I had changed it to **#main** again!😁

**Comment by neon-nyan** [comment]
Alright. But before we merge this PR.
Could you please tell me what this part does in the installer script?
```INI
[Run]
Filename: "{app}\CollapseLauncher.exe"; Description: "{cm:LaunchProgram,CollapseLauncher}"; Flags: runascurrentuser nowait postinstall skipifsilent; Check: returnTrue()
Filename: "{app}\CollapseLauncher.exe"; Flags: runascurrentuser; Parameters: "-install -svcName ""CollapseLauncher"" -svcDesc ""CollapseLauncher"" -mainExe ""CollapseLauncher.exe""  "; Check: returnFalse()```

**Comment by kleqing** [comment]
> Alright. But before we merge this PR. Could you please tell me what this part does in the installer script?
> 
> ```ini
> [Run]
> Filename: "{app}\CollapseLauncher.exe"; Description: "{cm:LaunchProgram,CollapseLauncher}"; Flags: runascurrentuser nowait postinstall skipifsilent; Check: returnTrue()
> Filename: "{app}\CollapseLauncher.exe"; Flags: runascurrentuser; Parameters: "-install -svcName ""CollapseLauncher"" -svcDesc ""CollapseLauncher"" -mainExe ""CollapseLauncher.exe""  "; Check: returnFalse()```
> ```

- Actually I didn't sure that if it was a feature of the Inno setup but I just add a feature which make the app run as adminstrator by adding flag: *runascurrentuser* to the script. I had done it in my project before [HoyoLauncher](https://github.com/kleqing/HoyoLauncher)

**Comment by neon-nyan** [comment]
I think we are okay to merge this.
About the translation, please make a new PR the next time you have something to fix with it.

Thank you again for your contribution!

**Pull request merged**
